spring.application.name=journalapp
server.port=8086
spring.data.mongodb.uri=mongodb+srv://shishodiakshitij123_db_user:eJFDGXYsqyktlnFm@cluster0.1toyzaw.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true