spring:
  application:
    name: journalapp

  redis:
    host: redis-18309.crce286.ap-south-1-1.ec2.cloud.redislabs.com
    port: 18309
    password: 6jaTvM2ryZOi2luWZziokfFB79IVuxHn


  data:
    mongodb:
      uri: mongodb+srv://shishodiakshitij123_db_user:eJFDGXYsqyktlnFm@cluster0.1toyzaw.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kshitijshishodia40@gmail.com
    password: rmpm hdsb lzex ohen
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true





server:
  port: 8086
  servlet:
    context-path: /journal

weather:
  api:
    key: 45f19de624d0069dcdcdd9ba16c5b01e
